# Generated by Django 5.2.8 on 2025-11-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreplyrule',
            name='workspace',
            field=models.CharField(default='current', max_length=64),
        ),
    ]
