# Generated by Django 5.2.8 on 2025-11-06 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_reply', '0002_autoreplyrule_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=64)),
                ('params', models.JSONField(blank=True, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='auto_reply.autoreplyrule')),
            ],
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=64)),
                ('condition', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('and_or', models.CharField(default='AND', max_length=8)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='auto_reply.autoreplyrule')),
            ],
        ),
    ]
