# Generated by Django 5.2.8 on 2025-11-10 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_reply', '0003_ruleaction_rulecondition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.TextField(blank=True, null=True)),
                ('subject_key', models.CharField(blank=True, help_text='Normalized subject key for dedupe when thread_id missing', max_length=255, null=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_logs', to='auto_reply.autoreplyrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'thread_id'], name='auto_reply__user_id_e7ac17_idx'), models.Index(fields=['user', 'to_email', 'subject_key'], name='auto_reply__user_id_ca9e71_idx'), models.Index(fields=['sent_at'], name='auto_reply__sent_at_e51e91_idx')],
            },
        ),
    ]
