# Generated by Django 5.2.8 on 2025-11-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_reply', '0004_replylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailtoken',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
