# Generated by Django 5.2.8 on 2025-11-11 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_reply', '0006_gmailsyncstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='replylog',
            name='inbound_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='replylog',
            constraint=models.UniqueConstraint(fields=('user', 'inbound_id'), name='uniq_replylog_user_inbound'),
        ),
    ]
