# Generated by Django 5.2.5 on 2025-11-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_reply', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature_image',
            field=models.CharField(blank=True, help_text='Path to uploaded signature image/GIF', max_length=255, null=True),
        ),
    ]
