# Generated by Django 5.2.8 on 2025-12-16 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_reply', '0009_userprofile_signature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='signature_html',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='signature_image',
        ),
    ]
